services:
  postgresql:
    container_name: letterboxdclone_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: letterboxdclone_admin
      POSTGRES_PASSWORD: admin123
      PGDATA: /var/lib/postgres/data
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - "5432:5432"
    networks:
      - letterboxdclone-net
    restart: unless-stopped

  pgadmin:
    container_name: letterboxdclone_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: letterboxdclone@gmail.com
      PGADMIN_DEFAULT_PASSWORD: letterboxdclone
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - letterboxdclone-net
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: letterboxdclone_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - letterboxdclone-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: letterboxdclone_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - letterboxdclone-net

networks:
  letterboxdclone-net:
    driver: bridge

volumes:
  postgres:
  pgadmin: